---
date: 2024-03-01
date-format: short
author: RWSC Steering Committee
editor: 
  markdown: 
    wrap: 72
---

# RWSC Conflict of Interest Policy

## Purpose {#purpose .unnumbered}

The purpose of the RWSC Conflict of Interest Policy is to provide
recommended definitions and processes for disclosure and decision-making
around potential or realized conflicts of interest while also maximizing
participation in all aspects of RWSC activities.

## Definitions and Application of Policy {#definitions .unnumbered}

Individuals serving on the RWSC Steering Committee, Sector Caucuses, or
Subcommittees have a “conflict of interest” if they receive of or have
**the potential to receive financial benefit (personal or via direct
relative) from agreements developed by RWSC**.

This policy shall apply to all members of the organization, as well as
to all staff employees, contractors, and individuals serving on the
Steering Committee, Sector Caucuses, and Subcommittees. Confirmation of
individuals’ agreement to the Policy will be requested verbally upon
appointment to the Steering Committee, Sector Caucuses, and
Subcommittees. The terms and conditions of this Policy will be reviewed
and made available to all participants prior to the discussion and
consideration of issues or decisions for which conflicts may be present
(e.g., funding decisions).

## **Notification and Disclosure** {#notif .unnumbered}

Whenever any individual has a potential or realized conflict of
interest, they shall promptly call such conflict to the attention of
Staff and/or the Steering Committee. This can be accomplished via
written electronic or verbal communication with Staff, with the
understanding that the communication will be shared with the Steering
Committee.

-   After identifying the issue, matter, or transaction with respect to
    which a conflict exists, an individual with a conflict shall
    withdraw from any further involvement in that issue, matter, or
    transaction unless a majority of the disinterested directors shall
    determine that the conflict is:

    -   Immaterial or not adverse to the interests of the organization;
        or

    -   The benefits of allowing the person with the conflict to
        participate in the discussion or consideration, but not the
        final decision, outweigh the dangers; in which case the person
        may participate in the discussion, study or consideration of the
        issue, matter or transaction, but not the final discussion or
        decision.

-   An individual who is uncertain as to whether they may have a
    conflict should ask the Director for an opinion. The Director shall
    issue a written opinion which shall be presumed to be correct and
    may be relied upon unless challenged by a Steering Committee member,
    in which case the final decision as to whether a conflict exists
    shall be made by the Steering Committee. The Director shall advise
    the Steering Committee of every opinion issued. Opinions shall, to
    the extent possible, avoid the disclosure of personal information
    while, at the same time, disclosing the basis for the opinion.
    Copies of all opinions shall be retained by the organization and
    made available to the Steering Committee upon request to permit and
    encourage consistency.

-   The minutes of the meeting at which the disclosure of any conflict
    is made shall reflect that the disclosure was made and whether the
    person with the conflict withdrew, after making full disclosure of
    the matter in question and the conflict, and was not present for the
    final discussion of the matter and any vote thereon.

## Contractually Related Conflicts of Interest {#contract .unnumbered}

An interested individual seeking a contract from the organization cannot
participate in a vote on assigning that contract, nor in any discussion
on the specific contract preceding such a vote. They will be shown as
abstaining due to a conflict of interest in the minutes of such a vote.
The interested individual can participate in any general grant policy
discussion or deliberations on whether a grant should be pursued.
